#!/usr/bin/env python

import sys
import json
import urllib

f = open(sys.argv[1])
data = json.load(f)
opts = {}
opts['url'] = data['request']['url']
opts['cookies'] = urllib.urlencode([(cookie['name'], cookie['value']) for cookie in data['request']['cookies']])
opts['http0'] = '-0' if data['request']['httpVersion'] == 'HTTP/1.0' else ''
opts['method'] = data['request']['method']
opts['headers'] = ' '.join(['-H "' + x['name'] + ': ' + x['value'] + '"' for x in data['request']['headers']])
if 'postData' in data['request']:
    opts['postData'] = data['request']['postData']['text']
else:
    opts['postData'] = ''

print 'curl -X {method} {http0} -b "{cookies}" {headers} -d "{postData}" {url}'.format(**opts)

